[tool.ruff.lint]
select = ["ALL"]

[tool.ruff]
ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D107", "FA102", "FBT001", "FBT002", "N802", "N803", "N806", "T201", "TRY003", "PD008", "ANN101"]
line-length = 200
select = ["PLR0913"]

[tool.ruff.pylint]
max-args = 10

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "docx.*,mailmerge.*,pulp.*"
ignore_missing_imports = true
